# Generated by Django 4.0.4 on 2022-05-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=20)),
                ('topics', models.CharField(max_length=100)),
                ('link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
