# Generated by Django 4.0.4 on 2022-05-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesDescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leetcode',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leetcode',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
