# Generated by Django 4.0.4 on 2022-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesDescription', '0002_leetcode_notes_alter_leetcode_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcode',
            name='link',
            field=models.URLField(),
        ),
    ]
