# Generated by Django 4.0.4 on 2022-05-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesDescription', '0004_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
    ]
