# Generated by Django 4.0.4 on 2022-05-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesDescription', '0005_remove_question_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='visitor',
        ),
    ]
